@startuml

start

: Borrower opens booking;
: Borrower selects "Return Vehicle";

if (Create and send data about the car?) then (yes)
 : Borrower creates car data;
 : Car data (GPS coordinates, photos,...)]
 : System sends car data to the lender's account;
else (no)
endif


if (Directly contact the lender?) then (yes)
 : Borrower directly contacts the lender;
else (no)
endif

: System creates notification;
: Notification]
: System sends notification to the lender's account;

: Lender opens application;
: Lender navigates to the booking detail;

if (Confirm the return of the vehicle) then (yes)
  
 : Lender confirms the return;
 
else (no)
 : Lender denies the return;
 : System presents means of solving issues with the return;
 while (Not all issues have been solved)
  : System presents means of solving issues with the return;
  : Lender tries to handle issues outside the app;
 endwhile (All issues solved)

endif

: Lender closes the booking;

stop
@enduml