@startuml
hide empty description

state "Return is initiated" as ReturnInitialization
state "Uploading car data" as CarDataUpload
state "Return waiting to be confirmed" as ReturnWaits

state "Return confirmed" as ReturnConfirmed
state "Booking closed" as BookingClosed
state "Resolving issues" as ResolvingIssues


[*] -> ReturnInitialization
ReturnInitialization -> CarDataUpload : Borrower decides\nto upload data
CarDataUpload -> ReturnWaits : Borrower confirmes\nthe return
ReturnInitialization -> ReturnWaits : Borrower confirmes\nthe return
ReturnWaits -d-> ReturnConfirmed : Lender confirmes\nthe return
ReturnWaits -> ResolvingIssues : Lender denies\nthe return
ResolvingIssues -> ReturnWaits : Lender has resolved\nall issues

ReturnConfirmed -> BookingClosed : Lender closes\nthe booking

BookingClosed ->[*]
@enduml